### ISSUE TITLE
windows在执行npm start 报无效的版本什么原因呢

### ISSUE THREAD

**Issue by qumj123** [purplestone/StarUML-language#2]
C:\Program Files\StarUML\resources>npm start
npm ERR! Invalid version: "0.1.6.0.1.0"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qumj\AppData\Roaming\npm-cache\_logs\2024-01-15T02_10_25_725Z-debug.log

**Comment by 2019211001001124-ZhangZiHao** [comment]
> C:\Program Files\StarUML\resources>npm start npm ERR! Invalid version: "0.1.6.0.1.0"
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\qumj\AppData\Roaming\npm-cache_logs\2024-01-15T02_10_25_725Z-debug.log

这个版本号可能是过长？ 可到 package.json 中将 version 修改即可，建议6.0.1

**Comment by hanekawasann** [comment]
`"version": "0.1.6.0.1.0"`
手动修改文件package.json中的版本号为
`"version": "0.1.6"`

**Comment by purplestone** [comment]
fixed from 6.1.0.0
