### ISSUE TITLE
请标明 Node.js 版本需求，预计是至少15

### ISSUE THREAD

**Issue by 2019211001001124-ZhangZiHao** [purplestone/StarUML-language#3]
warp.js 脚本中使用 replaceAll() ，为 Node.js 15 添加的新支持，使用15以下的版本将有 not a function异常

**Comment by hanekawasann** [comment]
可以自定函数解决
`String.prototype.replaceAllTxt = function replaceAll(search, replace) { return this.split(search).join(replace); }`
`var sFilePath = filePath.replaceAllTxt('/', path.sep);`

**Comment by purplestone** [comment]
fixed from v6.1.0.1 or up node to v18+
